---
  - name: Installing and Launch Metricbeat
    hosts: webservers
    become: yes
    tasks:

    - name: Download filebeat .deb file
      command: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.9.0-amd64.deb

    - name: Install filebeat .deb
      command: dpkg -i metricbeat-7.9.0-amd64.deb


    - name: Drop in metricbeat.yml
      copy:
        src: /etc/metricbeat/metricbeat.reference.yml
        dest: /etc/metricbeat/metricbeat.yml


    - name: Enable and Configure System Module
      command: metricbeat modules enable system